### ISSUE TITLE
Inconsistency around file scanning and file scan log messages

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/files_antivirus#53] opened 2015-06-26 17:48 UTC
### Steps to reproduce

1. Install 8.1 
2. Enable antivirus app
3. Set logging to everything
4. Upload a file from the webui or from cadaver

### Expected behaviour

There should be a message in the server log indicating that the file is being scanned.

### Actual behaviour

The message shows up sometimes.  I *think* that there's a cron job running that kicks off the scan which would explain why the messages are always different.  If this is the case, though, it's possible to upload files that don't get scanned and can allow for infected files to be uploaded when they shouldn't be.

I've seen instances where there are messages that the file is being scanned.  This usually looks like this:

```
{"reqId":"l77J7Z7\/sRBoagqfO0d0","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Scan started File: 17Account: at_admin Path: at_admin\/files\/pre_9.txt","level":0,"time":"2015-06-26T15:50:05+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"l77J7Z7\/sRBoagqfO0d0","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Scan is done File: 17Account: at_admin Path: at_admin\/files\/pre_9.txt","level":0,"time":"2015-06-26T15:50:05+00:00","method":"GET","url":"\/owncloud\/cron.php"}
```

I've seen instances where a scan summary message is written out but the name of the scanned file is not in the message.  This usually looks like this:
 
```
{"reqId":"aQ7XiBS\/h2PqroXLqoSN","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Exit code :: 0 Response :: stdin: OK\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 3855953\nEngine version: 0.98.7\nScanned directories: 0\nScanned files: 1\nInfected files: 0\nData scanned: 0.00 MB\nData read: 0.00 MB (ratio 0.00:1)\nTime: 5.873 sec (0 m 5 s)\n","level":0,"time":"2015-06-26T16:00:55+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/upload.php"}
```

I've seen instances where a scan summary message is written out with the name of the scanned file.  This usually looks like this:

```
{"reqId":"qNQbadYUbpBTdV0XDe0o","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Exit code :: 0 Response :: stdin: OK\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 3855953\nEngine version: 0.98.7\nScanned directories: 0\nScanned files: 1\nInfected files: 0\nData scanned: 0.00 MB\nData read: 0.00 MB (ratio 0.00:1)\nTime: 5.779 sec (0 m 5 s)\n","level":0,"time":"2015-06-26T15:31:13+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/upload.php"}
{"reqId":"ATDL4X51HBCJXLAesuXJ","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Exit code :: 0 Response :: stdin: OK\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 3855953\nEngine version: 0.98.7\nScanned directories: 0\nScanned files: 1\nInfected files: 0\nData scanned: 0.02 MB\nData read: 0.02 MB (ratio 1.00:1)\nTime: 5.785 sec (0 m 5 s)\n","level":0,"time":"2015-06-26T15:31:19+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Fpre_9.txt&c=7dbe83fe2cb2ae5ac8f5ea498666fcac&x=36&y=36&forceIcon=0"}
{"reqId":"ATDL4X51HBCJXLAesuXJ","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Exit code :: 0 Response :: stdin: OK\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 3855953\nEngine version: 0.98.7\nScanned directories: 0\nScanned files: 1\nInfected files: 0\nData scanned: 0.00 MB\nData read: 0.00 MB (ratio 0.00:1)\nTime: 5.792 sec (0 m 5 s)\n","level":0,"time":"2015-06-26T15:31:25+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Fpre_9.txt&c=7dbe83fe2cb2ae5ac8f5ea498666fcac&x=36&y=36&forceIcon=0"}
{"reqId":"jaPcSKs\/WElwUfOQrasL","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Scan started File: 17Account: at_admin Path: at_admin\/files\/pre_9.txt","level":0,"time":"2015-06-26T15:34:33+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"jaPcSKs\/WElwUfOQrasL","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Scan is done File: 17Account: at_admin Path: at_admin\/files\/pre_9.txt","level":0,"time":"2015-06-26T15:34:33+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"jaPcSKs\/WElwUfOQrasL","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Exit code :: 0 Response :: stdin: OK\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 3855953\nEngine version: 0.98.7\nScanned directories: 0\nScanned files: 1\nInfected files: 0\nData scanned: 0.00 MB\nData read: 0.00 MB (ratio 0.00:1)\nTime: 5.963 sec (0 m 5 s)\n","level":0,"time":"2015-06-26T15:34:39+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"jaPcSKs\/WElwUfOQrasL","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Scan started File: 24Account: at_admin Path: at_admin\/files\/eicar.com","level":0,"time":"2015-06-26T15:34:39+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"jaPcSKs\/WElwUfOQrasL","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Scan is done File: 24Account: at_admin Path: at_admin\/files\/eicar.com","level":0,"time":"2015-06-26T15:34:39+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"jaPcSKs\/WElwUfOQrasL","remoteAddr":"172.18.0.165","app":"files_antivirus","message":"Exit code :: 1 Response :: stdin: Eicar-Test-Signature FOUND\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 3855953\nEngine version: 0.98.7\nScanned directories: 0\nScanned files: 1\nInfected files: 1\nData scanned: 0.00 MB\nData read: 0.00 MB (ratio 0.00:1)\nTime: 5.976 sec (0 m 5 s)\n","level":0,"time":"2015-06-26T15:34:45+00:00","method":"GET","url":"\/owncloud\/cron.php"}

```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 RC1 (daily) Build:2015-06-26T03:11:01+00:00 9be1d08c3cb669f4829b0aa4af53d90cf3a9d153

**Comment by VicDeo** [comment] 2015-06-26 17:54
and?
it really does scans something that is a `file` and something that is `content written to a file`
fileId and filename is not available in the latter case (by design).

**Comment by jnfrmarks** [comment] 2015-06-26 18:02
When is the file supposed to be scanned?  At upload time?

I'm trying to test what happens when an infected file is upload to test #50.  I was expecting the file to be detected as infected and not uploaded (I using a file I downloaded from EICAR) but that isn't the case.

**Comment by VicDeo** [comment] 2015-06-26 18:10
@jnfrmarks 
1. the app sets a hook on writing access to any file on the wrapped storage. When the content is being written it is scanned for viruses on the fly
2. all files on user storages are scanned for viruses by cronjob.

**Comment by jnfrmarks** [comment] 2015-06-26 18:39
@VicDeo 

So, for #1 above, when I upload a file either from the WebUI or webdav to local storage, I should see messages in the server log file that the file is being scanned.

For #2, files will first be stored on the external storage and then scanned at some later point when the cron job is executed.

Is that right?

**Comment by jnfrmarks** [comment] 2015-06-26 18:58
This might just be a webdav issue.  I see the messages when uploading via webUI

@DeepDiver1975

**Comment by VicDeo** [comment] 2015-06-30 16:13
@jnfrmarks For #1 filename is not available when the content is scanned simultaneously with uploading it to OC. It is just a stream (a resource that contains data arriving in async mode until the End Of File event is triggered. )

**Comment by VicDeo** [comment] 2015-06-30 16:13
Webdav issue is addressed in https://github.com/owncloud/files_antivirus/pull/50

**Closed** 2015-09-22 20:44 UTC
