### ISSUE TITLE
Error Files_Antivirus\Cron\Task' not found

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/files_antivirus#46] opened 2015-05-22 08:36 UTC
An user sent following errors:

```
Error PHP require_once(): Failed opening required '/storage/web/web0002/web/apps/firewall/3rdparty/hoa/core/Parameter.php' (include_path='/storage/web/web0021/web/3rdparty/phpseclib/phpseclib/phpseclib:/storage/web/web0021/web/3rdparty/pear/pear_exception:/storage/web/web0021/web/3rdparty/pear/archive_tar:/storage/web/web0021/web/lib/private:/storage/web/web0021/web/config:/storage/web/web0021/web/3rdparty:/storage/web/web0021/web/apps:/storage/web/web0021/web/lib:.:/usr/local/share/pear:/storage/web/web0021/web') at /storage/web/web0021/web/apps/firewall/3rdparty/hoa/core/Core.php#72 2015-05-12T20:44:38+00:00 
Error PHP require_once(/storage/web/web0002/web/apps/firewall/3rdparty/hoa/core/Parameter.php): failed to open stream: Permission denied at /storage/web/web0021/web/apps/firewall/3rdparty/hoa/core/Core.php#72

Error PHP Class 'OCA\Files_Antivirus\OCA\Files_Antivirus\Cron\Task' not found at /storage/web/web0021/web/apps/files_antivirus/lib/backgroundscanner.php#112 2015-05-12T20:40:44+00:00 
Error	PHP	Class 'OCA\Files_Antivirus\OCA\Files_Antivirus\Cron\Task' not found at /storage/web/web0021/web/apps/files_antivirus/lib/backgroundscanner.php#112	2015-05-12T20:40:38+00:00
Error	PHP	Class 'OCA\Files_Antivirus\OCA\Files_Antivirus\Cron\Task' not found at /storage/web/web0021/web/apps/files_antivirus/lib/backgroundscanner.php#112	2015-05-12T20:40:28+00:00
Error	PHP	Class 'OCA\Files_Antivirus\OCA\Files_Antivirus\Cron\Task' not found at /storage/web/web0021/web/apps/files_antivirus/lib/backgroundscanner.php#112	2015-05-12T20:40:38+00:00
Error	PHP	Class 'OCA\Files_Antivirus\OCA\Files_Antivirus\Cron\Task' not found at /storage/web/web0021/web/apps/files_antivirus/lib/backgroundscanner.php#112
```

ClamAV is running and can be accessed manually.

### Server configuration

**Operating system**:
FreeBSD 9.3-RELEASE-p5

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4.13

**ownCloud version:**
8.0.2.0

@DeepDiver1975 could you check? Do you need more information? /cc @MorrisJobke 

00003143

**Comment by michaelstingl** [comment] 2015-05-22 21:10
@cdamken asked about cron configuration and pointed to docs:
https://doc.owncloud.com/server/8.0/admin_manual/configuration_server/antivirus_configuration.html#installing-clamav

User replied:
> clamAV does not run via contrab but is configured as a deamon. demaon gets its parameter and defintion by ist own.
> ClamAV as Demaon runs fine.
> owncloud is configured as Demaon(Socket).

**Comment by VicDeo** [comment] 2015-05-23 10:59
@michaelstingl it's already fixed https://github.com/owncloud/files_antivirus/pull/36/files

**Comment by michaelstingl** [comment] 2015-05-23 11:06
@VicDeo Thank you very much!

**Comment by VicDeo** [comment] 2015-05-25 13:58
Closing as a duplicate of https://github.com/owncloud/core/issues/15087

**Closed by VicDeo** 2015-05-25 13:58 UTC
Labels: blue-ticket
