### ISSUE TITLE
'HTTP/1.1 415 Unsupported Media Type' returned when virus found

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#177] opened 2017-08-31 10:35 UTC
when a virus is found the antivirus app returns `HTTP 415 UnsupportedMediaType` 
I feel `403 Forbidden` would be more suitable

**Comment by PVince81** [comment] 2017-09-05 09:47
This might be by design ? I seem to remember @michaelstingl mentioning this in another ticket.

**Comment by michaelstingl** [comment] 2017-09-05 11:54
I thought https://github.com/owncloud/core/pull/28620 fixed it. (Related: https://github.com/owncloud/enterprise/issues/2141)

**Comment by PVince81** [comment] 2017-09-05 11:57
https://github.com/owncloud/core/pull/28620 will parse the Sabre exception message as returned by the server. If the message says "Unsupported Media Type" then it will just display that. If we want something else, then the antivirus needs to provide a proper exception message to be displayed.

This ticket is rather about using 403 instead of 415. But I thought 415 was by design already, so we should probably keep it.

**Comment by michaelstingl** [comment] 2017-09-05 12:46
Oh, I understand. My concerns were more about the error message we receive in the body of the response.

**Comment by PVince81** [comment] 2017-09-14 16:07
moving to "development" for the next release

**Comment by PVince81** [comment] 2017-09-14 16:07
@VicDeo please help with the discussion above

**Comment by PVince81** [comment] 2017-11-03 13:53
moving to backlog

**Comment by VicDeo** [comment] 2018-04-11 14:29
Fixed with https://github.com/owncloud/files_antivirus/pull/219

**Closed by VicDeo** 2018-04-11 14:29 UTC
Labels: QA, p3-medium
