### ISSUE TITLE
files_antivirus breaks cronjob and fills log with an error

### ISSUE THREAD

**Issue by Rooie** [owncloud/files_antivirus#77] opened 2015-10-13 11:18 UTC
Hello,

After a couple of days of the install of my ownCloud instance, something unclear happened to the installation of which I haven't figured out yet.

When ownCloud wants to execute the cronjob, it returns this error:

`"fwrite(): send of 4 bytes failed with errno=32 Broken pipe at \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/scanner.php#68"`

and does not execute the cronjob.

I've disabled the files_antivirus app with the occ command, rebooted the server and waited until the cronjob was executed again, and it gave no problem at all.

Obviously I don't want to leave my antivirus disabled. I've seen more people with this issue but haven't found a solution yet. So if someone could help me out or at least explain why this is happening, I would be very grateful.

Sincerely,

A Linux beginner

#Additional information:
Ubuntu version:              14.04 LTS
ownCloud version:          8.1.3.0 
Antivirus App version:     0.7.0.1

**Comment by VicDeo** [comment] 2015-10-13 13:51
@Rooie exact duplicate of https://github.com/owncloud/files_antivirus/issues/77 so let's continue there
Please answer the questions in https://github.com/owncloud/files_antivirus/issues/69#issuecomment-144473673 and https://github.com/owncloud/files_antivirus/issues/69#issuecomment-144476899

Closed as a duplicate

**Closed by VicDeo** 2015-10-13 13:51 UTC
