### ISSUE TITLE
integrity check failed owncloud 9.0

### ISSUE THREAD

**Issue by ksbckr** [owncloud/files_antivirus#95] opened 2016-03-11 12:14 UTC
Hey there, just made an upgrade install via ubuntu package from 8.2.2.
The admin panel shows following error:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_antivirus
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [files_antivirus] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )
        )
)

```
Replaced the files_antivirus folder with the 9.0.0 tag from this repo, but error still exists. I'm not sure if its a problem of my config or the antivirus package itself, but I haven't had problems in previous versions.
Current system: Linux 3.16.0-60-generic #80~14.04.1-Ubuntu

**Comment by VicDeo** [comment] 2016-03-14 21:38
@LukasReschke How releases are supposed to be done now?

**Comment by carlaschroder** [comment] 2016-03-15 00:05
Confirming-- I see this too.

**Comment by RealRancor** [comment] 2016-03-15 06:35
@VicDeo How to sign the app is described here: https://doc.owncloud.org/server/9.0/developer_manual/app/code_signing.html#how-to-get-your-app-signed

**Comment by LukasReschke** [comment] 2016-03-15 09:13
> @LukasReschke How releases are supposed to be done now?

If the app is marked as official (which seems to be the case here) it needs to be signed.
See @RealRancor's link for information on how to sign the app.

**Comment by mholttech** [comment] 2016-03-15 15:11
I'm getting this same alert on my install

**Comment by carlaschroder** [comment] 2016-03-15 15:17
The AV app is reported in the app store as being updated, but I still get the integrity check error when I enable it.

**Comment by RealRancor** [comment] 2016-03-15 15:19
@mholttech @carlaschroder See the comment of @LukasReschke above. It is known that the app is not signed and that a new (signed) version needs to be released. :-)

**Comment by carlaschroder** [comment] 2016-03-15 16:32
I thought the update meant it had been signed.

**Comment by arjanvs** [comment] 2016-03-15 18:08
BTW the app is back in the app store :)

How can I check the signing?

**Comment by RealRancor** [comment] 2016-03-15 18:54
@arjanvs As you can read above the app needs to be signed first.

**Comment by arjanvs** [comment] 2016-03-15 19:03
I read that, but I wanted to check on my machine, if I can reproduce the initial failure. On my Debian 8.0 machine I have the app in the app store and I have it installed.

**Comment by carlaschroder** [comment] 2016-03-16 14:15
It still throws a failure on my test Ubuntu 15.10 system.
![antivirus-app-fails-check](https://cloud.githubusercontent.com/assets/8388387/13815183/ca0316f8-eb46-11e5-8112-e2f16fcc97b5.png)

**Comment by karlmikaelskar** [comment] 2016-03-16 21:27
I enabled the antivirus app and got the signature warning. 

 files_antivirus
    - EXCEPTION
        - OC\IntegrityCheck\Exceptions\InvalidSignatureException
        - Signature data not found.

But after some rescans and trying to enable the app again i get this:

- core
	- INVALID_HASH
		- .htaccess

**Comment by RealRancor** [comment] 2016-03-17 05:28
@karlmikaelskar This is unrelated to this app

**Comment by timscha** [comment] 2016-03-18 09:42
Any news on this? Tried to install the App on my ownCloud yesterday, but got the same error and a signature warning. Running owncloud on Debian 8 with nginx.

**Comment by RealRancor** [comment] 2016-03-18 09:47
I don't think it makes anything faster when constantly asking or stating that this is still an issue. It just floods the mailbox of users.

**Comment by LukasReschke** [comment] 2016-03-18 11:07
@VicDeo Please send a CSR request as described at https://doc.owncloud.org/server/9.0/developer_manual/app/code_signing.html#how-to-get-your-app-signed, then sign the app and upload that build and then these problems should all be gone :see_no_evil: 

This is caused because at some point the app was/is rated as Official.

**Comment by VicDeo** [comment] 2016-03-21 14:20
@LukasReschke done https://github.com/owncloud/appstore-issues/issues/54

**Comment by VicDeo** [comment] 2016-03-21 15:45
reuploaded to appstore. file signes for 0.8.01 can be taken from https://github.com/owncloud/files_antivirus/releases/download/stable9-0.8.0.1/files_antivirus.tar.gz
`files_antivirus/appinfo/signature.json` and copied to `/pathto/owncloud/apps/files_antivirus/appinfo/signature.json`. or just reinstall the app to download signed version

**Comment by carlaschroder** [comment] 2016-03-21 15:51
yay, no more warning! Thanks @VicDeo

**Comment by carlaschroder** [comment] 2016-03-21 15:51
For 9.0.

**Comment by VicDeo** [comment] 2016-03-22 20:56
>core
INVALID_HASH
.htaccess

owncloud/core#22966
owncloud/core#22982

**Closed** 2016-03-22 20:56 UTC
